services:
    cece74.sharethis.listener:
        class: cece74\sharethis\event\listener
        arguments:
            - @config
            - @template
            - @user
            - @request
            - %core.root_path%
        tags:
            - { name: event.listener }
           
